---
title: "Comparing `distalr`'s pairwise-alignment backends"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

Here is a small test set of tale cds sequences (5 = 2 groups of 2 + outlier)

```{r}
library(tantale)
tellTaleSubjSeqsFile <- system.file("extdata", "bai3_sample_tal_genomic_regions.fasta", package = "tantale", mustWork = T)
telltale_dir <- system.file("extdata", "tellTaleExampleOutput", package = "tantale", mustWork = T)
# 
# tantale::tell_tales(subject_file = tellTaleSubjSeqsFile,
#                           output_dir = telltale_dir
# )
```

# Parse annotale output (rvd, aa, dna, domain type, array id) in a tell_tales output dir

```{r parse tale parts from tell_tales output dir}
tale_parts <- tale_parts(system.file("extdata", "tellTaleExampleOutput", package = "tantale", mustWork = T))
```


## Run `distalr` to investigate TALE protein domains composition relatedness

```{r use distalr}


dres <- distalr(tale_parts = tale_parts, h_cut = 10, ncores = 6,
                aln_method = "Biostrings")

# dres2 <- distalr(tale_parts = tale_parts, h_cut = 10, ncores = 6,
#                 aln_method = "mmseq2", conda_bin = "/home/cunnac/bin/miniconda3/condabin/conda")

dres3 <- distalr(tale_parts = tale_parts, h_cut = 10, ncores = 6,
                aln_method = "DECIPHER")

```


