
##### Utility functions ####
## -convert TALE RVD sequences into different formats
## - run external TALE clustering tools (FuncTALE and AnnoTALE)











#### run external TALE RVD sequences inferrence and clustering tools ####

#' Runs the "predict" and "analyze" steps of AnnoTALE on a fasta file.
#'
#' A R wrapper around the
#' \href{https://www.ncbi.nlm.nih.gov/pubmed/26876161}{AnnoTALE} 'AnnoTALE.jar
#' predict' and 'AnnoTALE.jar analyze' shell calls. The whole AnnoTALE workflow
#' can be completed by a subsequent call to the \code{\link{run_annotale_build}}
#' function.
#'
#' @param fasta_file Path to a fasta file containing DNA (?) sequences to be
#'   analyzed for TALE content.
#' @param output_dir Directory where output will be written (created if does not
#'   exist).
#' @param prefix A scalar character vector containing a prefix that will be
#'   appended to TALE names by AnnoTALE. If not supplied, the function will try
#'   to guess the prefix from the input file name.
#' @param annotale_jar Path to the AnnoTALE jar file if you want to use another
#'   version than the one provided with tantale.
#' @return Returns invisibly the exit code of the shell call to the last
#'   AnnoTALE step (ie '0' if successful).
#' @export
#' @family external TALE tools
run_annotale_predict <- function(fasta_file,
                            output_dir = getwd(),
                            prefix = NULL,
                            annotale_jar = system.file("tools", "AnnoTALEcli-1.5.jar", package = "tantale", mustWork = T)
                            ) {
  # Define output dirs for the various stages of AnnoTALE
  stopifnot(dir.exists(output_dir) || dir.create(path = output_dir, showWarnings = TRUE, recursive = TRUE, mode = "775"))
  predict_dir <- file.path(output_dir, "Predict")
  analyze_dir <- file.path(output_dir, "Analyze")
  # Define a prefix for TALEs (the strain or assembly ID) derived from the genome file name.
  if( is.null(prefix) ) {
  prefix <- gsub(pattern = "^(.*)\\.(fasta|fa|fas)$" , replacement  = "\\1", basename(fasta_file), perl = TRUE)
  }
  # Run the "predict" stage of AnnoTALE
  comPredict <- paste0(
    "java -jar ", annotale_jar,
    " predict",
    " g=", fasta_file,
    " s=", prefix,
    " outdir=", predict_dir
  )
  cli::cli_inform(c("Running AnnoTALE predict for {.val {prefix}}", " " = "{comPredict}"))
  exitPredict <- system(comPredict)
  if (exitPredict != 0) {
    cli::cli_abort("AnnoTALE predict failed with exit status {exitPredict}.",
                   class = c("tantale_error_annotale_failed", "tantale_error"))
  }

  # Run the "analyze" stage of AnnoTALE
  comAnalyze <- paste0(
    "java -jar ", annotale_jar,
    " analyze ",
    " t=", shQuote(list.files(predict_dir, pattern = "^TALE_DNA_sequences_", full.names = TRUE)),
    " outdir=", shQuote(analyze_dir)
  )
  cli::cli_inform(c("Running AnnoTALE analyze for {.val {prefix}}", " " = "{comAnalyze}"))
  exitAnalyze <- system(comAnalyze)
  return(invisible(exitAnalyze))
}






#' Run the "build" stage of AnnoTALE.
#'
#' A R wrapper around the \href{https://www.ncbi.nlm.nih.gov/pubmed/26876161}{AnnoTALE} 'AnnoTALE.jar build' program.
#' It usually takes is input from the file generated by the \code{\link{run_annotale_predict}}
#' function.
#'
#' @param fasta_file Path to a fasta file containing TALE sequences as
#'   returned by AnnoTALE (?) to be classified into groups.
#' @param output_dir Directory where output will be written (created if does not
#'   exist).
#' @param annotale_jar Path to the AnnoTALE jar file if you want to use another
#'   version than the one provided with tantale.
#' @return Returns invisibly the exit code of the shell call to Annotale (ie '0' if successful).
#' @export
#' @family external TALE tools
run_annotale_build <- function(fasta_file,
                          output_dir = getwd(),
                          annotale_jar = system.file("tools", "AnnoTALEcli-1.5.jar", package = "tantale", mustWork = T)
                          ) {
  if(! dir.exists(output_dir)) dir.create(path = output_dir, showWarnings = TRUE, recursive = TRUE, mode = "775")
  comBuild <- paste0(
    "java -Xms512M -Xmx6G -jar ", annotale_jar,
    " build ",
    " t=", shQuote(fasta_file),
    " outdir=", shQuote(output_dir)
  )
  cli::cli_inform(c("Running AnnoTALE build", " " = "{comBuild}"))
  exitBuild <- system(comBuild)
  return(invisible(exitBuild))
}



#' Run functal from QueTAL to build a phylogenetic tree of TALE RVD sequences.
#'
#' A R wrapper around the \href{https://doi.org/10.3389/fpls.2015.00545}{QueTAL} 'functal' perl script.
#'
#' @param tal_file Path to a QueTAL-formatted file of TALE RVD sequences.
#' @param tree_format Tree layout passed to functal's `-n` option (default `"fan"`).
#' @param output_prefix Prefix used for functal's output file names.
#' @param output_dir Directory where output will be copied (default: current working directory).
#' @param functal_path Path to the functal perl script if you want to use another
#'   version than the one provided with tantale.
#' @param conda_bin Path to your Conda binary file if you need to specify a
#'   non-standard location, otherwise leave to "auto".
#' @return Returns invisibly the exit code of the shell call to functal (ie '0' if successful).
#' @export
#' @family external TALE tools
functal <- function(tal_file,
                    tree_format = "fan",
                    output_prefix = "FuncTALE",
                    output_dir = getwd(),
                    functal_path = system.file("tools", "QueTAL_v1.1", "FuncTAL", "FuncTAL_v.1.1.pl", package = "tantale", mustWork = T),
                    conda_bin = "auto") {
  # Running functal from QueTAL_v1.1
  # A few observations:
  # Refuse to use another output directory than the "Ouputs" one in the program folder
  # Cannot invoke the program from another working directory than the one where the pl script is located
  # Crashes on some real-world CDS inputs; not yet isolated to a specific cause
  # So here is a caller function to get around these issues:

  functal_dir <- dirname(functal_path)

  # Assembling the command to be run
  # -I functal_dir is required for perl to find Statistics.pm, which ships
  # alongside the script rather than as an installed module. List::MoreUtils
  # and Bio::Perl come from the 'tantale' conda environment.
  functal_cmd <- paste(shQuote(.tantale_bin("perl", conda_bin = conda_bin)),
                       "-I", shQuote(functal_dir), shQuote(functal_path),
                      "-n", tree_format,
                      shQuote(tal_file),
                      shQuote(output_prefix))

  # Run the command inside the tantale conda environment
  cli::cli_inform(c("Running functal", " " = "{functal_cmd}"))
  envReady <- !as.logical(.create_tantale_env(conda_bin = conda_bin))
  if (envReady) {
    exitCom <- .tantale_exec(functal_cmd, cwd = functal_dir,
                             check = FALSE, what = "FuncTAL")
  } else {
    .abort_no_env("FuncTAL")
  }
  if (exitCom != 0) {
    cli::cli_abort(
      c("FuncTAL failed with perl exit status {exitCom}.",
        "i" = "See the console output above for what it reported."),
      class = c("tantale_error_functal_failed", "tantale_error"))
  }

  # Transferring the ouput to the output dir and deleting it in the functal "Outputs" directory
  functal_output_files <-
    list.files(file.path(functal_dir, "Outputs"), full.names = TRUE)
  file.copy(
    from = functal_output_files,
    to = output_dir,
    overwrite = FALSE,
    recursive = FALSE,
    copy.mode = TRUE,
    copy.date = TRUE
  )
  unlink(functal_output_files, recursive = TRUE, force = FALSE)
  return(invisible(exitCom))
}
