
##### Utility functions ####
## -convert TALE RVD sequences into different formats
## - run external TALE clustering tools (FuncTALE and AnnoTALE)











#### run external TALE RVD sequences inferrence and clustering tools ####

#' Runs the "predict" and "analyze" steps of AnnoTALE on a fasta file
#'
#' An R wrapper around the
#' \href{https://www.ncbi.nlm.nih.gov/pubmed/26876161}{AnnoTALE} 'AnnoTALE.jar
#' predict' and 'AnnoTALE.jar analyze' shell calls. The whole AnnoTALE workflow
#' can be completed by a subsequent call to the \code{\link{run_annotale_build}}
#' function.
#'
#' @param fasta_file Path to a fasta file containing DNA sequences (e.g. a
#'   genome assembly) to be analyzed for TALE content.
#' @param output_dir Directory where output will be written (created if it does not
#'   exist).
#' @param prefix A scalar character vector containing a prefix that will be
#'   appended to TALE names by AnnoTALE. If not supplied, the function will try
#'   to guess the prefix from the input file name.
#' @param annotale_jar Path to the AnnoTALE jar file. The default is the
#'   copy [tantale_setup()] downloads; give a path to use another version.
#' @return \code{0}, invisibly; called for the files it writes to
#'   \code{output_dir}. If either stage exits with a non-zero status, the
#'   function stops with an error of class
#'   \code{tantale_error_annotale_failed}.
#' @export
#' @family external TALE tools
#' @examples
#' \donttest{
#' # Needs a Java runtime, and the tools and genomes tantale_setup() downloads.
#' fasta <- tantale_genome("MAI1")
#' out <- file.path(tempdir(), "annotale_predict_example")
#' run_annotale_predict(fasta, output_dir = out)
#' list.files(file.path(out, "Predict"))
#' }
run_annotale_predict <- function(fasta_file,
                            output_dir = getwd(),
                            prefix = NULL,
                            annotale_jar = .tantale_tool("annotale")
                            ) {
  # Define output dirs for the various stages of AnnoTALE
  stopifnot(dir.exists(output_dir) || dir.create(path = output_dir, showWarnings = TRUE, recursive = TRUE, mode = "775"))
  predict_dir <- file.path(output_dir, "Predict")
  analyze_dir <- file.path(output_dir, "Analyze")
  # Define a prefix for TALEs (the strain or assembly ID) derived from the genome file name.
  if( is.null(prefix) ) {
  prefix <- gsub(pattern = "^(.*)\\.(fasta|fa|fas)$" , replacement  = "\\1", basename(fasta_file), perl = TRUE)
  }
  # Run the "predict" stage of AnnoTALE
  comPredict <- paste0(
    "java -jar ", shQuote(annotale_jar),
    " predict",
    " g=", shQuote(fasta_file),
    " s=", shQuote(prefix),
    " outdir=", shQuote(predict_dir)
  )
  cli::cli_inform(c("Running AnnoTALE predict for {.val {prefix}}", " " = "{comPredict}"))
  .annotale_exec(comPredict, "predict")

  # Run the "analyze" stage of AnnoTALE
  comAnalyze <- paste0(
    "java -jar ", annotale_jar,
    " analyze ",
    " t=", shQuote(list.files(predict_dir, pattern = "^TALE_DNA_sequences_", full.names = TRUE)),
    " outdir=", shQuote(analyze_dir)
  )
  cli::cli_inform(c("Running AnnoTALE analyze for {.val {prefix}}", " " = "{comAnalyze}"))
  .annotale_exec(comAnalyze, "analyze")
}






#' Run the "build" stage of AnnoTALE
#'
#' An R wrapper around the \href{https://www.ncbi.nlm.nih.gov/pubmed/26876161}{AnnoTALE} 'AnnoTALE.jar build' program.
#' It usually takes its input from the file generated by the \code{\link{run_annotale_predict}}
#' function.
#'
#' @param fasta_file Path to a \code{TALE_DNA_sequences_*} fasta file, as
#'   written by \code{\link{run_annotale_predict}}'s "predict" stage, to be
#'   classified into groups.
#' @param output_dir Directory where output will be written (created if it does not
#'   exist).
#' @param annotale_jar Path to the AnnoTALE jar file. The default is the
#'   copy [tantale_setup()] downloads; give a path to use another version.
#' @return \code{0}, invisibly; called for the files it writes to
#'   \code{output_dir}. If AnnoTALE exits with a non-zero status, the
#'   function stops with an error of class
#'   \code{tantale_error_annotale_failed}.
#' @export
#' @family external TALE tools
#' @examples
#' \donttest{
#' # Needs a Java runtime and the tools tantale_setup() downloads. Chained
#' # from run_annotale_predict()'s own output, since that is the file build
#' # normally classifies.
#' fasta <- tantale_genome("MAI1")
#' predict_out <- file.path(tempdir(), "annotale_build_example", "predict")
#' run_annotale_predict(fasta, output_dir = predict_out)
#' predicted <- list.files(file.path(predict_out, "Predict"),
#'                         pattern = "^TALE_DNA_sequences_", full.names = TRUE)
#' build_out <- file.path(tempdir(), "annotale_build_example", "build")
#' run_annotale_build(predicted, output_dir = build_out)
#' list.files(build_out)
#' }
run_annotale_build <- function(fasta_file,
                          output_dir = getwd(),
                          annotale_jar = .tantale_tool("annotale")
                          ) {
  if(! dir.exists(output_dir)) dir.create(path = output_dir, showWarnings = TRUE, recursive = TRUE, mode = "775")
  comBuild <- paste0(
    "java -Xms512M -Xmx6G -jar ", shQuote(annotale_jar),
    " build ",
    " t=", shQuote(fasta_file),
    " outdir=", shQuote(output_dir)
  )
  cli::cli_inform(c("Running AnnoTALE build", " " = "{comBuild}"))
  .annotale_exec(comBuild, "build")
}


#' Run one AnnoTALE stage and stop if it fails
#'
#' AnnoTALE's jar is run with the system Java, outside the conda
#' environment, so it goes through \code{.tantale_exec()} for the exit
#' status check and then raises AnnoTALE's own condition class.
#'
#' @param command The shell command.
#' @param stage The AnnoTALE stage, for the message ("predict", "analyze",
#'   "build").
#' @param quiet If \code{TRUE}, discard AnnoTALE's standard output and keep
#'   its standard error for the error message; if \code{FALSE}, both reach
#'   the console as they are written.
#' @return \code{0}, invisibly.
#' @noRd
.annotale_exec <- function(command, stage, quiet = FALSE) {
  errFile <- NULL
  if (quiet) {
    errFile <- tempfile("annotale_stderr")
    on.exit(unlink(errFile), add = TRUE)
    command <- paste(command, "> /dev/null")
  }
  status <- .tantale_exec(command, stderr_file = errFile, check = FALSE)
  if (!identical(as.integer(status), 0L)) {
    saidWhy <- if (!is.null(errFile) && file.exists(errFile)) {
      utils::tail(readLines(errFile, warn = FALSE), 5)
    } else character()
    # AnnoTALE's text is shown verbatim, braces included.
    saidWhy <- gsub("}", "}}", gsub("{", "{{", saidWhy, fixed = TRUE), fixed = TRUE)
    cli::cli_abort(
      c("AnnoTALE {stage} failed with exit status {status}.",
        if (length(saidWhy)) c("i" = "It said:"),
        stats::setNames(saidWhy, rep(" ", length(saidWhy)))),
      class = c("tantale_error_annotale_failed", "tantale_error"))
  }
  invisible(0L)
}
