
##### Utility functions ####
## -convert TALE RVD sequences into different formats
## - run external TALE clustering tools (FuncTALE and AnnoTALE)











#### run external TALE RVD sequences inferrence and clustering tools ####

#' Runs the "predict" and "analyze" steps of AnnoTALE on a fasta file.
#'
#' A R wrapper around the
#' \href{https://www.ncbi.nlm.nih.gov/pubmed/26876161}{AnnoTALE} 'AnnoTALE.jar
#' predict' and 'AnnoTALE.jar analyze' shell calls. The whole AnnoTALE workflow
#' can be completed by a subsequent call to the \code{\link{run_annotale_build}}
#' function.
#'
#' @param fasta_file Path to a fasta file containing DNA sequences (e.g. a
#'   genome assembly) to be analyzed for TALE content.
#' @param output_dir Directory where output will be written (created if does not
#'   exist).
#' @param prefix A scalar character vector containing a prefix that will be
#'   appended to TALE names by AnnoTALE. If not supplied, the function will try
#'   to guess the prefix from the input file name.
#' @param annotale_jar Path to the AnnoTALE jar file if you want to use another
#'   version than the one provided with tantale.
#' @return Returns invisibly the exit code of the shell call to the last
#'   AnnoTALE step (ie '0' if successful).
#' @export
#' @family external TALE tools
#' @examples
#' \donttest{
#' # Needs a Java runtime.
#' fasta <- system.file("extdata", "MAI1.fa", package = "tantale")
#' out <- file.path(tempdir(), "annotale_predict_example")
#' run_annotale_predict(fasta, output_dir = out)
#' list.files(file.path(out, "Predict"))
#' }
run_annotale_predict <- function(fasta_file,
                            output_dir = getwd(),
                            prefix = NULL,
                            annotale_jar = system.file("tools", "AnnoTALEcli-1.5.jar", package = "tantale", mustWork = T)
                            ) {
  # Define output dirs for the various stages of AnnoTALE
  stopifnot(dir.exists(output_dir) || dir.create(path = output_dir, showWarnings = TRUE, recursive = TRUE, mode = "775"))
  predict_dir <- file.path(output_dir, "Predict")
  analyze_dir <- file.path(output_dir, "Analyze")
  # Define a prefix for TALEs (the strain or assembly ID) derived from the genome file name.
  if( is.null(prefix) ) {
  prefix <- gsub(pattern = "^(.*)\\.(fasta|fa|fas)$" , replacement  = "\\1", basename(fasta_file), perl = TRUE)
  }
  # Run the "predict" stage of AnnoTALE
  comPredict <- paste0(
    "java -jar ", annotale_jar,
    " predict",
    " g=", fasta_file,
    " s=", prefix,
    " outdir=", predict_dir
  )
  cli::cli_inform(c("Running AnnoTALE predict for {.val {prefix}}", " " = "{comPredict}"))
  exitPredict <- system(comPredict)
  if (exitPredict != 0) {
    cli::cli_abort("AnnoTALE predict failed with exit status {exitPredict}.",
                   class = c("tantale_error_annotale_failed", "tantale_error"))
  }

  # Run the "analyze" stage of AnnoTALE
  comAnalyze <- paste0(
    "java -jar ", annotale_jar,
    " analyze ",
    " t=", shQuote(list.files(predict_dir, pattern = "^TALE_DNA_sequences_", full.names = TRUE)),
    " outdir=", shQuote(analyze_dir)
  )
  cli::cli_inform(c("Running AnnoTALE analyze for {.val {prefix}}", " " = "{comAnalyze}"))
  exitAnalyze <- system(comAnalyze)
  return(invisible(exitAnalyze))
}






#' Run the "build" stage of AnnoTALE.
#'
#' A R wrapper around the \href{https://www.ncbi.nlm.nih.gov/pubmed/26876161}{AnnoTALE} 'AnnoTALE.jar build' program.
#' It usually takes is input from the file generated by the \code{\link{run_annotale_predict}}
#' function.
#'
#' @param fasta_file Path to a \code{TALE_DNA_sequences_*} fasta file, as
#'   written by \code{\link{run_annotale_predict}}'s "predict" stage, to be
#'   classified into groups.
#' @param output_dir Directory where output will be written (created if does not
#'   exist).
#' @param annotale_jar Path to the AnnoTALE jar file if you want to use another
#'   version than the one provided with tantale.
#' @return Returns invisibly the exit code of the shell call to Annotale (ie '0' if successful).
#' @export
#' @family external TALE tools
#' @examples
#' \donttest{
#' # Needs a Java runtime. Chained from run_annotale_predict()'s own output,
#' # since that is the file build normally classifies.
#' fasta <- system.file("extdata", "MAI1.fa", package = "tantale")
#' predict_out <- file.path(tempdir(), "annotale_build_example", "predict")
#' run_annotale_predict(fasta, output_dir = predict_out)
#' predicted <- list.files(file.path(predict_out, "Predict"),
#'                         pattern = "^TALE_DNA_sequences_", full.names = TRUE)
#' build_out <- file.path(tempdir(), "annotale_build_example", "build")
#' run_annotale_build(predicted, output_dir = build_out)
#' list.files(build_out)
#' }
run_annotale_build <- function(fasta_file,
                          output_dir = getwd(),
                          annotale_jar = system.file("tools", "AnnoTALEcli-1.5.jar", package = "tantale", mustWork = T)
                          ) {
  if(! dir.exists(output_dir)) dir.create(path = output_dir, showWarnings = TRUE, recursive = TRUE, mode = "775")
  comBuild <- paste0(
    "java -Xms512M -Xmx6G -jar ", annotale_jar,
    " build ",
    " t=", shQuote(fasta_file),
    " outdir=", shQuote(output_dir)
  )
  cli::cli_inform(c("Running AnnoTALE build", " " = "{comBuild}"))
  exitBuild <- system(comBuild)
  return(invisible(exitBuild))
}
